name: Test and build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory '*'
          golangci-lint run -v ./...

  build:
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: golang:trixie
    steps:
      - uses: actions/checkout@v4
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          go build -mod vendor -ldflags "-X 'main.BuildTimeStamp=$(date +%s)' -X 'main.AppVersion=${{ env.RELEASE_VERSION }}'" -o ncatos .
      - name: Archive builds
        uses: actions/upload-artifact@v4
        with:
          name: ncatos-build
          path: |
            ncatos
            config/config.yml
            systemd/ncatos.service
